# Generated by Django 5.2.9 on 2025-12-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsection',
            name='page',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
