# Generated by Django 5.2.9 on 2026-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyoverview_contactinfo_footercontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoverview',
            name='image',
            field=models.ImageField(blank=True, upload_to='company_overview/'),
        ),
        migrations.AddField(
            model_name='missioncontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='mission_content/'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
