# Generated by Django 5.2.9 on 2026-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoverview',
            name='process_image',
            field=models.ImageField(blank=True, upload_to='company_overview/'),
        ),
    ]
